language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install
  - pipenv install -d

script:
  - pipenv shell && coverage run --source=src setup.py test

after_success:
  - coveralls

env:
  - PIPENV_IGNORE_VIRTUALENVS=1
